apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: zavashop-github-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zavashop.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ required "workloadIdentity.clientId is required" .Values.workloadIdentity.clientId | quote }}
    keyvaultName: {{ required "keyVault.name is required" .Values.keyVault.name | quote }}
    tenantId: {{ required "tenantId is required" .Values.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: GITHUB-TOKEN
          objectType: secret
  secretObjects:
    - secretName: github-token
      type: Opaque
      data:
        - objectName: GITHUB-TOKEN
          key: token
