apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ required "workloadIdentity.clientId is required" .Values.workloadIdentity.clientId | quote }}
  labels:
    {{- include "zavashop.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
