apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zavashop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/part-of: zavashop
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
